In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [4]:
col_comercial = [
    "lv_datcom_id_datcom",
    "producto",
    "contrato",
    "nombre_de_usuario",
    "direccion_oficial",
    "direccion_de_instalacion",
    "identificacion_direccion",
    "fecha_de_instalacion",
    "tipo_producto",
    "categoria",
    "subcategoria",
    "localidad",
    "barrio",
    "plan_de_facturacion",
    "estado_de_corte",
    "cuentas_energia",
    "saldo_energia",
    "creacion_producto",
    "retiro_de_producto",
    "ciclo",
    "nombre_usuario_oficial",
    "direccion",
    "cuentas_total",
    "saldo_total",
    "fecha_cargue"
]

col_consumo = [
    "lv_cons_id_cons",
    "ano",
    "mes",
    "consumo",
    "producto",
    "lv_fecha_server",
    "lv_user"
]

col_med = [
    "lv_datme_id_datme",
    "producto",
    "cliente",
    "aparato",
    "fecha_de_instalacion",
    "multiplo",
    "digitos",
    "fecha_cargue"
]

In [5]:
df_com = pd.read_csv('../../data/EMCALI/lv_data_comercial.csv')
df_com.columns = col_comercial

/var/folders/t9/n67k3lts6wl76ntfbg_ntw3w0000gn/T/ipykernel_36306/3661465880.py:1: DtypeWarning: Columns (0,16) have mixed types. Specify dtype option on import or set low_memory=False.
  df_com = pd.read_csv('../../data/EMCALI/lv_data_comercial.csv')

In [6]:
df_com.head()

,lv_datcom_id_datcom,producto,contrato,nombre_de_usuario,direccion_oficial,direccion_de_instalacion,identificacion_direccion,fecha_de_instalacion,tipo_producto,categoria,subcategoria,localidad,barrio,plan_de_facturacion,estado_de_corte,cuentas_energia,saldo_energia,creacion_producto,retiro_de_producto,ciclo,nombre_usuario_oficial,direccion,cuentas_total,saldo_total,fecha_cargue
0,1154157,1117913.0,721816.0,HUGO ARMANDO GARCIA HEREDIA,CR 27 A 44-50,K 27A 44 50,1976247.0,2005-09-11,6140.0,1.0,3.0,76001.0,1207.0,500.0,1.0,0.0,0,2005-11-09,2032-12-31,26.0,HUGO ARMANDO GARCIA HEREDIA,NaN,0.0,0.0,2025-07-18 11:44:08.642622
1,1154158,1117918.0,721817.0,JOSE EGIDIO GOMEZ ALVAREZ,CR 27 A 44-53,K 27A 44 53,1976252.0,2005-08-16,6140.0,1.0,3.0,76001.0,1207.0,500.0,1.0,0.0,0,2005-08-16,2032-12-31,26.0,MARIA ALDERY MUÑOZ CARDONA,NaN,0.0,0.0,2025-07-18 11:44:08.642622
2,1154159,1117923.0,721818.0,NOHEMY GIRALDO,CR 27 A 44-56,K 27A 44 56,1976258.0,1986-09-25,6140.0,1.0,3.0,76001.0,1207.0,500.0,1.0,0.0,0,1986-09-25,2032-12-31,26.0,NOHEMY GIRALDO,NaN,0.0,0.0,2025-07-18 11:44:08.642622
3,1154160,1117928.0,721819.0,JULIO E BUITRAGO BUITRAGO,CR 27 A 44-59,K 27A 44 59,1976262.0,1996-06-11,6140.0,1.0,3.0,76001.0,1207.0,500.0,1.0,0.0,0,2010-11-18,2032-12-31,26.0,HENRY PEREZ TOBAR,NaN,0.0,0.0,2025-07-18 11:44:08.642622
4,1154161,1117933.0,721820.0,VICENCIA BALANTA,CR 27 A 44-62,K 27A 44 62,1976268.0,2005-01-14,6140.0,1.0,3.0,76001.0,1207.0,500.0,1.0,1.0,80754,2005-01-14,2032-12-31,26.0,VICENCIA BALANTA,NaN,1.0,195399.0,2025-07-18 11:44:08.642622

In [7]:
df_com.tipo_producto.value_counts()

tipo_producto
6140.0    895482
6361.0     14458
Name: count, dtype: int64

In [9]:
df_cons = pd.read_csv('../../data/EMCALI/lv_data_consumo.csv')
df_cons.columns = col_consumo

In [10]:
df_cons.ano.min(), df_cons.mes.min()

(np.int64(2024), np.int64(1))

In [11]:
df_cons.sort_values(by=['producto', 'ano', 'mes'], inplace=True)
df_cons

,lv_cons_id_cons,ano,mes,consumo,producto,lv_fecha_server,lv_user
903354,1,2024,9,0,2,2025-06-17 19:26:15.899116,NaN
1805706,902353,2024,10,340,2,2025-06-17 19:28:41.631768,NaN
2708058,1804705,2024,11,0,2,2025-06-17 19:31:05.999564,NaN
3610410,2707057,2024,12,0,2,2025-06-17 19:33:29.081817,NaN
4512762,3609409,2025,1,0,2,2025-06-17 19:35:55.727311,NaN
...,...,...,...,...,...,...,...
9026150,8122797,2025,5,0,898474572,2025-07-18 12:30:15.985604,NaN
899127,9029415,2025,6,0,898474572,2025-07-18 12:31:28.967772,NaN
8122210,7218857,2025,4,0,898535648,2025-06-25 15:57:04.133346,1.061696e+09
9026151,8122798,2025,5,0,898535648,2025-07-18 12:30:15.985604,NaN
899128,9029416,2025,6,0,898535648,2025-07-18 12:31:28.967772,NaN

In [12]:
df_cons['fecha'] = pd.to_datetime(
	df_cons.rename(columns={'ano': 'year', 'mes': 'month'})[['year', 'month']].assign(day=1)
)

In [14]:
df = df_cons.merge(df_com[['producto', 'localidad', 'barrio', 'tipo_producto', 'categoria', 'subcategoria']], on='producto', how='left', indicator=True)
df.drop(columns=['lv_fecha_server', 'lv_user'], inplace=True)

In [15]:
df._merge.value_counts()

_merge
both          9031695
left_only        1946
right_only          0
Name: count, dtype: int64

In [16]:
df

,lv_cons_id_cons,ano,mes,consumo,producto,fecha,localidad,barrio,tipo_producto,categoria,subcategoria,_merge
0,1,2024,9,0,2,2024-09-01,76001.0,102.0,6140.0,1.0,1.0,both
1,902353,2024,10,340,2,2024-10-01,76001.0,102.0,6140.0,1.0,1.0,both
2,1804705,2024,11,0,2,2024-11-01,76001.0,102.0,6140.0,1.0,1.0,both
3,2707057,2024,12,0,2,2024-12-01,76001.0,102.0,6140.0,1.0,1.0,both
4,3609409,2025,1,0,2,2025-01-01,76001.0,102.0,6140.0,1.0,1.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...
9033636,8122797,2025,5,0,898474572,2025-05-01,NaN,NaN,NaN,NaN,NaN,left_only
9033637,9029415,2025,6,0,898474572,2025-06-01,NaN,NaN,NaN,NaN,NaN,left_only
9033638,7218857,2025,4,0,898535648,2025-04-01,NaN,NaN,NaN,NaN,NaN,left_only
9033639,8122798,2025,5,0,898535648,2025-05-01,NaN,NaN,NaN,NaN,NaN,left_only
9033640,9029416,2025,6,0,898535648,2025-06-01,NaN,NaN,NaN,NaN,NaN,left_only

In [17]:
df_sin_comercial = df[df._merge == 'left_only']
df = df[df._merge == 'both']
df.drop(columns=['_merge'], inplace=True)

/var/folders/t9/n67k3lts6wl76ntfbg_ntw3w0000gn/T/ipykernel_36306/7878263.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['_merge'], inplace=True)

In [18]:
df_sin_comercial.to_csv('../../data/EMCALI/lv_data_consumo_sin_comercial.csv', index=False)

In [40]:
df.fecha.min(), df.fecha.max()

(Timestamp('2024-09-01 00:00:00'), Timestamp('2025-06-01 00:00:00'))

In [42]:
df

,lv_cons_id_cons,ano,mes,consumo,producto,fecha,localidad,barrio,tipo_producto,categoria,subcategoria
0,1,2024,9,0,2,2024-09-01,76001.0,102.0,6140.0,1.0,1.0
1,902353,2024,10,340,2,2024-10-01,76001.0,102.0,6140.0,1.0,1.0
2,1804705,2024,11,0,2,2024-11-01,76001.0,102.0,6140.0,1.0,1.0
3,2707057,2024,12,0,2,2024-12-01,76001.0,102.0,6140.0,1.0,1.0
4,3609409,2025,1,0,2,2025-01-01,76001.0,102.0,6140.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
9033588,9033639,2025,6,0,16037818,2025-06-01,76001.0,1599.0,6140.0,1.0,2.0
9033589,8127022,2025,5,0,16037821,2025-05-01,76001.0,1599.0,6140.0,1.0,2.0
9033590,9033640,2025,6,0,16037821,2025-06-01,76001.0,1599.0,6140.0,1.0,2.0
9033591,8127023,2025,5,0,16038136,2025-05-01,76001.0,1598.0,6140.0,1.0,1.0
9033592,9033641,2025,6,0,16038136,2025-06-01,76001.0,1598.0,6140.0,1.0,1.0

In [ ]:
df.to_csv('../../data/EMCALI/datos_procesados/consumo_010924_010625.csv', index=False)

In [41]:
df.fecha

0         2024-09-01
1         2024-10-01
2         2024-11-01
3         2024-12-01
4         2025-01-01
             ...
9033588   2025-06-01
9033589   2025-05-01
9033590   2025-06-01
9033591   2025-05-01
9033592   2025-06-01
Name: fecha, Length: 9031695, dtype: datetime64[ns]

## Inspecciones

In [3]:
df_anomalias = pd.read_excel('../../data/EMCALI/lv_lega_insp_irregularidad_report02102025.xlsx')
df_anomalias.head()

,Prog Orden Trafo,Prog Plan,Prog Subplan,Prog SubEstacion,Prog Circuito,Prog Trafo,Prog Nodo,Prog Fecha,Prog Tecnico,Insp Trafo,Insp Nodo,Orden Interna,Orden Externa,Amarre,Identificar Trafo,Identificar Nodo,Tiene Producto?,Fecha Visita,Contrato,Producto,Nombre Usuario,Direccion,Estado Servicio,Facturas Vencidas,Tarifa,Consumo 1,Consumo 2,Consumo 3,Prog Medidor,Medidor,Multiplo,Medidor Testigo,Lectura,Altura,Ubicacion de Medidor,Frontera,Codigo Frontera,Material Acometida,Conexion Acometida,Calibre Acometida,Nodo Acometida,Anomalia 1,Anomalia 2,Anomalia 3,Anomalia 4,Corriente 1,Corriente 2,Corriente 3,Actividad Comercial,Nombre Establecimiento,Energia Proyectada,Metodo Aplicado,Observacion,Fecha Server,Insp Cliente Tecnico,Fecha Server.1
0,1770,VINCULO CLIENTE RED,MACROMEDICION,CENTRO,CALLE 15,E20855,1179497,30/09/2025,1234197019 - LUIS ALFREDO LLANOS RABA,E20855,1179497.0,29647,102888,1 - PERTENECE,NaN,NaN,SI,30/09/2025,247522,319301,ELKIN RAUL GIRALDO GIRALDO -,CL 15 7-116,1,1,8,1285.0,1091.0,1025.0,GLMN_60154378,GLMN_60154378,1,NO,70089,2 - MENOR A 1.8 METROS,3 - GABINETE,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,6,0,E_S3 - SELLOS DE TAPA PRINCIPAL ROTOS,D_M19 - MEDIDOR SIN TAPA BORNERA,NaN,NaN,0.0,0.0,0.0,23803 - LOCAL,NaN,0,6 - NO APLICA,NaN,01/10/2025 10:47:13,1234197019 - LUIS ALFREDO LLANOS RABA,29/09/2025 16:34:25
1,1770,VINCULO CLIENTE RED,MACROMEDICION,CENTRO,CALLE 15,E20855,1179497,30/09/2025,1234197019 - LUIS ALFREDO LLANOS RABA,E20855,1179497.0,29665,102906,1 - PERTENECE,NaN,NaN,SI,30/09/2025,420519,573526,HERNAN FRANCO RESTREPO,CL 15 8-47,1,0,2,2803.0,2614.0,3377.0,NaN,D33A_037295612453,0,NO,0,2 - MENOR A 1.8 METROS,2 - PARED,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,6,0,E_M13 - MEDIDOR ESTATICO CON DISPLAY APAGADO O...,NaN,NaN,NaN,0.0,0.0,0.0,23803 - LOCAL,NaN,0,6 - NO APLICA,Se encuentra medidor en terreno: D33A_03729561...,01/10/2025 11:15:12,1234197019 - LUIS ALFREDO LLANOS RABA,29/09/2025 16:34:27
2,1770,VINCULO CLIENTE RED,MACROMEDICION,CENTRO,CALLE 15,E20855,1179497,30/09/2025,1234197019 - LUIS ALFREDO LLANOS RABA,E20855,1179497.0,29668,102909,1 - PERTENECE,NaN,NaN,SI,30/09/2025,254371,335360,LEONARDO DE JESUS BOTERO ARISTIZABAL,CL 15 8-58 LC 0000,1,0,2,2768.0,2356.0,2804.0,E4AA_1095768,E4AA_1095768,1,NO,0,2 - MENOR A 1.8 METROS,3 - GABINETE,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,6,0,"E_M12 - MEDIDOR DAÑADO (PARTIDO, QUEMADA,PERFO...",NaN,NaN,NaN,0.0,0.0,0.0,23803 - LOCAL,NaN,0,6 - NO APLICA,NaN,01/10/2025 11:19:13,1234197019 - LUIS ALFREDO LLANOS RABA,29/09/2025 16:34:27
3,1770,VINCULO CLIENTE RED,MACROMEDICION,CENTRO,CALLE 15,E20855,1179497,30/09/2025,1234197019 - LUIS ALFREDO LLANOS RABA,E20855,1179497.0,29863,103042,4 - ADICIONAR,NaN,NaN,NO,30/09/2025,0,0,0,SIN DIRECCIÓN,0,0,0,NaN,NaN,NaN,NaN,ESEC_59607,0,NO,4934,2 - MENOR A 1.8 METROS,3 - GABINETE,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,6,0,E_A8 - SERVICIO CLANDESTINO,NaN,NaN,NaN,0.0,0.0,0.0,23785 - OTRO,NaN,0,6 - NO APLICA,Medidor aparece en Open en modo libre,01/10/2025 14:50:04,1234197019 - LUIS ALFREDO LLANOS RABA,NaN
4,1770,VINCULO CLIENTE RED,MACROMEDICION,CENTRO,CALLE 15,E20855,1179497,30/09/2025,1234197019 - LUIS ALFREDO LLANOS RABA,E20855,1179497.0,29864,103043,4 - ADICIONAR,NaN,NaN,NO,30/09/2025,0,0,0,SIN DIRECCIÓN,0,0,0,NaN,NaN,NaN,NaN,FTEE_1038767,0,NO,2930,2 - MENOR A 1.8 METROS,3 - GABINETE,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,6,0,E_A8 - SERVICIO CLANDESTINO,NaN,NaN,NaN,0.0,0.0,0.0,23785 - OTRO,NaN,0,6 - NO APLICA,Medidor sin registro en Open,01/10/2025 14:50:49,1234197019 - LUIS ALFREDO LLANOS RABA,NaN

In [4]:
df_anomalias.shape, df_anomalias.drop_duplicates().shape

((2495, 56), (2480, 56))

In [5]:
df_anomalias.drop_duplicates(inplace=True)

In [34]:
df_anomalias[df_anomalias['Producto']==319156]#['Anomalia 1'].value_counts(dropna=False)

,Prog Orden Trafo,Prog Plan,Prog Subplan,Prog SubEstacion,Prog Circuito,Prog Trafo,Prog Nodo,Prog Fecha,Prog Tecnico,Insp Trafo,Insp Nodo,Orden Interna,Orden Externa,Amarre,Identificar Trafo,Identificar Nodo,Tiene Producto?,Fecha Visita,Contrato,Producto,Nombre Usuario,Direccion,Estado Servicio,Facturas Vencidas,Tarifa,Consumo 1,Consumo 2,Consumo 3,Prog Medidor,Medidor,Multiplo,Medidor Testigo,Lectura,Altura,Ubicacion de Medidor,Frontera,Codigo Frontera,Material Acometida,Conexion Acometida,Calibre Acometida,Nodo Acometida,Anomalia 1,Anomalia 2,Anomalia 3,Anomalia 4,Corriente 1,Corriente 2,Corriente 3,Actividad Comercial,Nombre Establecimiento,Energia Proyectada,Metodo Aplicado,Observacion,Fecha Server,Insp Cliente Tecnico,Fecha Server.1
111,1700,VINCULO CLIENTE RED,MACROMEDICION,CENTRO,CALLE 15,E16119,1179527,03/09/2025,10296334 - GUIOVANNI MARTÍNEZ INGA,E16119,1179527.0,27528,100766,2 - NO PERTENECE,E16746,1179551.0,SI,09/09/2025,247466,319156,DELIO LONDOO VELEZ Y CIA,CL 15 6-54,1,0,2,3873.0,3274.0,3750.0,T4SK_50436405,T4SK_50436405,1,NO,35622,2 - MENOR A 1.8 METROS,3 - GABINETE,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,4,19,D_S5 - SIN SELLO BORNERA,"E_M12 - MEDIDOR DAÑADO (PARTIDO, QUEMADA,PERFO...",NaN,NaN,0.0,0.0,0.0,23803 - LOCAL,NaN,0,6 - NO APLICA,Validar foto en la orden 1698,09/09/2025 13:56:06,10296334 - GUIOVANNI MARTÍNEZ INGA,02/09/2025 15:41:17
115,1698,VINCULO CLIENTE RED,MACROMEDICION,CENTRO,CALLE 15,E16746,1179551,03/09/2025,1113665720 - JONATHAN MORALES VALDÉS,E16746,1179551.0,27611,100840,4 - ADICIONAR,NaN,NaN,SI,03/09/2025,247466,319156,DELIO LONDOO VELEZ Y CIA,CL 15 6-54,1,0,2,3873.0,3274.0,3750.0,NaN,T4SK_50436405,1,NO,35622,2 - MENOR A 1.8 METROS,3 - GABINETE,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,4,19,D_S5 - SIN SELLO BORNERA,"E_M12 - MEDIDOR DAÑADO (PARTIDO, QUEMADA,PERFO...",NaN,NaN,0.0,0.0,0.0,23803 - LOCAL,NaN,0,6 - NO APLICA,NaN,16/09/2025 14:01:25,1104804316 - Estefania Giraldo Daza,NaN

In [20]:
df_anomalos = df_anomalias[df_anomalias['Producto']!=0][['Fecha Visita', 'Producto', 'Direccion', 'Anomalia 1', 'Anomalia 2', 'Anomalia 3', 'Anomalia 4', 'Actividad Comercial']].copy()
df_anomalos['anomalo'] = 1
df_anomalos.rename(columns={'Fecha Visita': 'fecha_visita', 'Producto': 'producto', 'Direccion': 'direccion'}, inplace=True)
df_anomalos['fecha_visita'] = pd.to_datetime(df_anomalos.fecha_visita)

/var/folders/t9/n67k3lts6wl76ntfbg_ntw3w0000gn/T/ipykernel_53487/4236699508.py:4: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_anomalos['fecha_visita'] = pd.to_datetime(df_anomalos.fecha_visita)

In [39]:
df_anomalos.to_csv('../../data/EMCALI/datos_procesados/info_anomalos.csv', index=False)

In [7]:
df_inspecciones = pd.read_excel('../../data/EMCALI/INSPECCIONES_REALIZADAS.xlsx')
df_inspecciones.head()

,Prog Orden Trafo,Prog Plan,Prog Subplan,Prog SubEstacion,Prog Circuito,Prog Trafo,Prog Nodo,Prog Fecha,Prog Tecnico,Prog Gestor,Insp Acceso Trafo,Causal de No Acceso al Transformador,Insp Trafo,Insp Nodo,Insp Trafo Paralelo,Insp Medidor Macro,Insp Trafo Tecnico,Orden Trafo,Orden Interna,Orden Externa,Amarre,Identificar Trafo,Identificar Nodo,Tiene Producto?,Fecha Visita,Contrato,Producto,Nombre Usuario,Direccion,Estado Servicio,Facturas Vencidas,Tarifa,Consumo 1,Consumo 2,Consumo 3,Prioridad,Prog Medidor,Medidor,Multiplo,Medidor Testigo,Lectura,Altura,Ubicacion de Medidor,Frontera,Codigo Frontera,Material Acometida,Conexion Acometida,Calibre Acometida,Nodo Acometida,Anomalia 1,Anomalia 2,Anomalia 3,Anomalia 4,Corriente 1,Corriente 2,Corriente 3,Actividad Comercial,Nombre Establecimiento,Energia Proyectada,Metodo Aplicado,Observacion,Programado,Insp Cliente Tecnico,Fecha Server
0,1,VINCULO CLIENTE RED,ESPECIALES,CHIPICHAPE,LOS CERROS,E16017,5928371,2025-04-01,1114875087 - YERSON ANDRES CABRERA VILLEGAS,NaN,SI,1 - FIBRA,E3613,5928371.0,NO TIENE,ILEGIBLE,1114875087 - YERSON ANDRES CABRERA VILLEGAS,Orden Interna 1 - E16017,60,60,4 - ADICIONAR,NaN,NaN,SI,01/04/2025,1277041,1975276,LUIS CARLOS GRILLO,CASA CARLOS GRILLO,1,1,1,13.0,30.0,30.0,0 - NO APLICA,NaN,B3SK_70801290,1,NaN,29973.0,2 - MENOR A 1.8 METROS,2 - PARED,NO,NaN,2 - ALUMINIO,3 - AEREA CONCENTRICA,6,0.0,E_M8 - MEDIDOR CON DISCO FRENADO,E_M17 - MEDIDOR CON DIGITOS CORRIDOS,NaN,NaN,0.0,0.0,0.0,23781 - RESIDENCIAL,Casa 214 vda las palmas,0.0,6 - NO APLICA,Vda las palmas,NO,1114875087 - YERSON ANDRES CABRERA VILLEGAS,01/04/2025 0:00:00
1,1,VINCULO CLIENTE RED,ESPECIALES,CHIPICHAPE,LOS CERROS,E16017,5928371,2025-04-01,1114875087 - YERSON ANDRES CABRERA VILLEGAS,NaN,SI,1 - FIBRA,E3613,5928371.0,NO TIENE,ILEGIBLE,1114875087 - YERSON ANDRES CABRERA VILLEGAS,Orden Interna 1 - E16017,56,56,4 - ADICIONAR,NaN,NaN,SI,01/04/2025,1279359,7757514,MARIA LIGIA RAMIREZ -,PISO 2 VDA LAS PALMAS,4,2,1,568.0,561.0,540.0,0 - NO APLICA,NaN,C2SB_51005682,1,NaN,57046.0,1 - MAYOR IGUAL A 1.8 METROS,2 - PARED,NO,NaN,2 - ALUMINIO,3 - AEREA CONCENTRICA,6,1579347.0,CO - CONFORME,NaN,NaN,NaN,0.0,0.0,0.0,23781 - RESIDENCIAL,NaN,0.0,6 - NO APLICA,Piso 2 vda las palmas,NO,1114875087 - YERSON ANDRES CABRERA VILLEGAS,01/04/2025 0:00:00
2,1,VINCULO CLIENTE RED,ESPECIALES,CHIPICHAPE,LOS CERROS,E16017,5928371,2025-04-01,1114875087 - YERSON ANDRES CABRERA VILLEGAS,NaN,SI,1 - FIBRA,E3613,5928371.0,NO TIENE,ILEGIBLE,1114875087 - YERSON ANDRES CABRERA VILLEGAS,Orden Interna 1 - E16017,58,58,4 - ADICIONAR,NaN,NaN,SI,01/04/2025,268791,389231,WILLIAM PEÑUELA REINA,VDA LAS PALMAS,1,0,1,105.0,97.0,99.0,0 - NO APLICA,NaN,C2SB_51006793,1,NaN,19047.0,1 - MAYOR IGUAL A 1.8 METROS,2 - PARED,NO,NaN,2 - ALUMINIO,3 - AEREA CONCENTRICA,6,1579347.0,CO - CONFORME,NaN,NaN,NaN,0.0,0.0,0.0,23781 - RESIDENCIAL,NaN,0.0,6 - NO APLICA,Vda las palmas,NO,1114875087 - YERSON ANDRES CABRERA VILLEGAS,01/04/2025 0:00:00
3,1,VINCULO CLIENTE RED,ESPECIALES,CHIPICHAPE,LOS CERROS,E16017,5928371,2025-04-01,1114875087 - YERSON ANDRES CABRERA VILLEGAS,NaN,SI,1 - FIBRA,E3613,5928371.0,NO TIENE,ILEGIBLE,1114875087 - YERSON ANDRES CABRERA VILLEGAS,Orden Interna 1 - E16017,59,59,4 - ADICIONAR,NaN,NaN,SI,01/04/2025,1277687,1976707,JORGE ELIECER APONTE,VEREDA LAS PALMAS,1,0,1,212.0,229.0,227.0,0 - NO APLICA,NaN,C2SB_51005352,1,NaN,64677.0,1 - MAYOR IGUAL A 1.8 METROS,2 - PARED,NO,NaN,2 - ALUMINIO,3 - AEREA CONCENTRICA,6,0.0,D_A15 - ACOMETIDA Y CARGA SE ENCUENTRAN POR LA...,NaN,NaN,NaN,0.0,0.0,0.0,23781 - RESIDENCIAL,Casa 204,0.0,6 - NO APLICA,Vda las palmas,NO,1114875087 - YERSON ANDRES CABRERA VILLEGAS,01/04/2025 0:00:00
4,3,VINCULO CLIENTE RED,ESPECIALES,CENTRO,CALLE 14,E13234,1177133,2025-04-01,10296334 - GUIOVANNI MARTÍNEZ INGA,16896932.0,NO,3 - SUBTERRANEO,ILEGIBLE,1177133.0,NO TIENE,NO APLICA,31993135 - LUZ ELENA PINO,Orden Interna 3 - E13234,516,516,4 - ADICIONAR,0,0.0,SI,08/04/2025,247102,318213,CARLOS ANTONIO NARANJO FULLER,CL 14 5-21 APTO 200,1,0,1,324.0,265.0,321.0,NaN,NaN,C2AA_139804,1,NO,17894.0,1 - MAYOR IGUAL A 1.8 METROS,2 - PARED,NO,NaN,1 - COBRE,4 - SUBTERRANEA ABIERTA,4,0.0,CO - CONFORME,NaN,NaN,NaN,0.0,0.0,0.0,23785 - OTRO,0,0.0,6 - NO APLICA,NaN,SI,31993135 - LUZ ELENA PINO,08/04/2025 0:00:00

In [8]:
df_inspecciones.shape, df_inspecciones.drop_duplicates().shape

((19102, 64), (18957, 64))

In [9]:
df_inspecciones.drop_duplicates(inplace=True)

In [10]:
df_inspecciones.Producto.value_counts(dropna=False)

Producto
0           2143
375431         3
10951286       3
11362617       3
1962298        3
            ...
15989600       1
15982928       1
15982929       1
322847         1
318264         1
Name: count, Length: 16461, dtype: int64

In [17]:
df_inspecciones[df_inspecciones['Producto']==375431]#['Anomalia 1'].value_counts(dropna=False)

,Prog Orden Trafo,Prog Plan,Prog Subplan,Prog SubEstacion,Prog Circuito,Prog Trafo,Prog Nodo,Prog Fecha,Prog Tecnico,Prog Gestor,Insp Acceso Trafo,Causal de No Acceso al Transformador,Insp Trafo,Insp Nodo,Insp Trafo Paralelo,Insp Medidor Macro,Insp Trafo Tecnico,Orden Trafo,Orden Interna,Orden Externa,Amarre,Identificar Trafo,Identificar Nodo,Tiene Producto?,Fecha Visita,Contrato,Producto,Nombre Usuario,Direccion,Estado Servicio,Facturas Vencidas,Tarifa,Consumo 1,Consumo 2,Consumo 3,Prioridad,Prog Medidor,Medidor,Multiplo,Medidor Testigo,Lectura,Altura,Ubicacion de Medidor,Frontera,Codigo Frontera,Material Acometida,Conexion Acometida,Calibre Acometida,Nodo Acometida,Anomalia 1,Anomalia 2,Anomalia 3,Anomalia 4,Corriente 1,Corriente 2,Corriente 3,Actividad Comercial,Nombre Establecimiento,Energia Proyectada,Metodo Aplicado,Observacion,Programado,Insp Cliente Tecnico,Fecha Server
3237,187,VINCULO CLIENTE RED,ESPECIALES,DIESEL I,SAN NICOLAS,E16459,1029681,2025-05-14,10296334 - GUIOVANNI MARTÍNEZ INGA,16896932.0,SI,1 - FIBRA,E16459,1029681.0,NO TIENE,U4AA_2008568,1143983522 - Daniel Felipe Arce Medina,Orden Interna 187 - E16459,4264,4264,4 - ADICIONAR,NaN,NaN,SI,14/05/2025,264448,375431,ALVARO CORREDOR CORONADO,CL 18 7-109,1,0,1,169.0,197.0,182.0,0 - NO APLICA,NaN,EIEM_21770942,1,NaN,62511.0,1 - MAYOR IGUAL A 1.8 METROS,2 - PARED,NO,NaN,2 - ALUMINIO,3 - AEREA CONCENTRICA,6,0.0,CO - CONFORME,NaN,NaN,NaN,0.0,0.0,0.0,23781 - RESIDENCIAL,Vivienda,0.0,6 - NO APLICA,Medidor en caja metálica CL 18 7-109,NO,10296334 - GUIOVANNI MARTÍNEZ INGA,14/05/2025 0:00:00
6081,260,VINCULO CLIENTE RED,ESPECIALES,DIESEL II,CALLE 19,E19263,1012916,2025-05-29,1113665720 - JONATHAN MORALES VALDÉS,76333111.0,SI,1 - FIBRA,E19263,1012916.0,NO TIENE,F4SI_70816150,1061716620 - Kennedy Zuñiga Cerón,Orden Interna 260 - E19263,27991,101140,4 - ADICIONAR,NaN,NaN,SI,11/09/2025,264448,375431,ALVARO CORREDOR CORONADO,CL 18 7-109,1,0,1,169.0,197.0,182.0,NaN,NaN,EIEM_21770942,1,NO,63094.0,1 - MAYOR IGUAL A 1.8 METROS,2 - PARED,NO,NaN,2 - ALUMINIO,3 - AEREA CONCENTRICA,6,5.0,NA - NO APLICA,NaN,NaN,NaN,0.0,0.0,0.0,23794 - FABRICACION DE MUEBLES,NaN,197.0,4 - POR DIFERENCIA DE LECTURAS,Caja con candado,NO,1113665720 - JONATHAN MORALES VALDÉS,11/09/2025 8:10:59
7014,282,VINCULO CLIENTE RED,ESPECIALES,DIESEL I,OBRERO,E18901,1033352,2025-06-03,1114875087 - YERSON ANDRES CABRERA VILLEGAS,76333111.0,SI,1 - FIBRA,E18901,1033352.0,NO TIENE,F4SI_70818077,1114875087 - YERSON ANDRES CABRERA VILLEGAS,Orden Interna 282 - E18901,8139,8139,3 - NO ENCONTRADO,0,0.0,SI,05/06/2025,264448,375431,ALVARO CORREDOR CORONADO,CL 18 7-109,1,0,1,169.0,197.0,182.0,0 - NO APLICA,EIEM_21770942,EIEM_21770942,1,NaN,0.0,3 - NO APLICA,4 - NO APLICA,NO,NaN,3 - NO APLICA,8 - NO APLICA,NO APLICA,0.0,NA - NO APLICA,NaN,NaN,NaN,0.0,0.0,0.0,0 - NO APLICA,NaN,0.0,6 - NO APLICA,NaN,SI,1114875087 - YERSON ANDRES CABRERA VILLEGAS,05/06/2025 0:00:00

In [15]:
df_inspec = df_inspecciones[df_inspecciones['Producto']!=0][['Fecha Visita', 'Producto', 'Direccion', 'Anomalia 1', 'Anomalia 2', 'Anomalia 3', 'Anomalia 4', 'Actividad Comercial']].copy()
df_inspec['anomalo'] = 1
df_inspec.rename(columns={'Fecha Visita': 'fecha_visita', 'Producto': 'producto', 'Direccion': 'direccion'}, inplace=True)
df_inspec['fecha_visita'] = pd.to_datetime(df_inspec.fecha_visita, format='mixed')

In [18]:
df_inspec.loc[df_inspec['Anomalia 1']=='CO - CONFORME', 'anomalo'] = 0
df_inspec.loc[df_inspec['Anomalia 1']=='NA - NO APLICA', 'anomalo'] = np.nan
df_inspec.anomalo.value_counts(dropna=False)

anomalo
NaN    9579
0.0    4345
1.0    2890
Name: count, dtype: int64

In [16]:
df_inspec.shape, df_inspec.drop_duplicates().shape

((16814, 9), (16699, 9))

In [19]:
df_inspec.fecha_visita.min(), df_inspec.fecha_visita.max()

(Timestamp('2025-01-04 00:00:00'), Timestamp('2025-12-09 00:00:00'))

In [21]:
df_inspec.sort_values(by=['producto', 'fecha_visita'], inplace=True)
df_anomalos.sort_values(by=['producto', 'fecha_visita'], inplace=True)

In [22]:
df_inspec.head()

,fecha_visita,producto,direccion,Anomalia 1,Anomalia 2,Anomalia 3,Anomalia 4,Actividad Comercial,anomalo
11957,2025-07-07,1234,SIN DIRECCIÓN,CO - CONFORME,NA - NO APLICA,NA - NO APLICA,NA - NO APLICA,23810 - DISCOTECA,0.0
11956,2025-07-07,2212,AV 5 OESTE 16-12,E_A1 - ACOMETIDA DERIVADA,D_A2 - ACOMETIDA EMPALMADA,D_A5 - ACOMETIDA QUEMADA,D_A4 - ACOMETIDA PELADA ANTES DEL MEDIDOR,23839 - CASETA DE VIGILANTE,1.0
17521,2025-08-09,3134,AV 5 OESTE 21-52,D_A10 - ACOMETIDA DENTRO DEL TECHO,NaN,NaN,NaN,23781 - RESIDENCIAL,1.0
3974,2025-11-06,3872,AV 4 A OESTE 28-39,NA - NO APLICA,NaN,NaN,NaN,0 - NO APLICA,NaN
3973,2025-11-06,3876,AV 4 A OESTE 28-35,NA - NO APLICA,NaN,NaN,NaN,0 - NO APLICA,NaN

In [24]:
df_inspec.to_csv('../../data/EMCALI/datos_procesados/info_inspecciones.csv', index=False)

In [23]:
df_anomalos.head()

,fecha_visita,producto,direccion,Anomalia 1,Anomalia 2,Anomalia 3,Anomalia 4,Actividad Comercial,anomalo
850,2025-07-07,2212,AV 5 OESTE 16-12,E_A1 - ACOMETIDA DERIVADA,D_A2 - ACOMETIDA EMPALMADA,D_A5 - ACOMETIDA QUEMADA,D_A4 - ACOMETIDA PELADA ANTES DEL MEDIDOR,23839 - CASETA DE VIGILANTE,1
718,2025-07-30,40669,CL 6 A 26-55,E_M13 - MEDIDOR ESTATICO CON DISPLAY APAGADO O...,NaN,NaN,NaN,23781 - RESIDENCIAL,1
1077,2025-06-10,50344,CL 5 37 A-09 APTO 201,E_M13 - MEDIDOR ESTATICO CON DISPLAY APAGADO O...,NaN,NaN,NaN,23781 - RESIDENCIAL,1
1078,2025-06-10,50353,CL 5 37 A-19,E_M2 - ALTERACION DE LA POSICION DEL MEDIDOR (...,NaN,NaN,NaN,23803 - LOCAL,1
716,2025-07-28,70088,CR 27 3-80,E_M2 - ALTERACION DE LA POSICION DEL MEDIDOR (...,NaN,NaN,NaN,23781 - RESIDENCIAL,1

In [38]:
df_anomalos.fecha_visita.min(), df_anomalos.fecha_visita.max()

(Timestamp('2025-01-08 00:00:00'), Timestamp('2025-10-02 00:00:00'))

In [11]:
df_anomalias.Producto.value_counts(dropna=False)

Producto
0          2148
319156        2
603418        1
583466        1
583486        1
           ...
2437566       1
2437575       1
2457500       1
2457336       1
573526        1
Name: count, Length: 332, dtype: int64